/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  integration:
    "react-1-xDf3-j1SnWhOPyR5X-6HOB56aBZmpd1mTvtPO76i0j2ZBSLf4yoj5HpFirKEJyUbOw7V7MXKk0K-xu5uisWrn-7vlZmr1P4nlEAfxlT6RuaA3sSpriT0XAOP",
  tt: "tt-1-V5KxTL1rpmHbDPY-BwuRvR4X3-6-3AX33H5vBaIi6Pc=",
  version: "2020-11-20",
};

export default ebconfig;
